'use client';

import { useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ImagePlus, X } from 'lucide-react';
import Stars from './Stars';
import { saveReviewAction, deleteReviewAction } from '@/features/reviews/actions';
import type { Review } from '@/server/dal/reviews';
import { runAction } from '@/features/shared/runAction';

/** The extension is generated by the upload route, so it can be trusted. */
const isVideo = (path: string) => /\.(mp4|webm|mov)$/i.test(path);

/**
 * Write (or rewrite) a review.
 *
 * Only rendered for a verified buyer — the server decides that, and re-checks
 * it in saveReviewAction, because a client component can be called directly.
 * Editing an approved review sends it back to moderation, which is why the copy
 * says so rather than letting it silently disappear from the page.
 */
export default function ReviewForm({ productId, existing }: {
  productId: number;
  existing: Review | null;
}) {
  const router = useRouter();
  const fileRef = useRef<HTMLInputElement>(null);
  const [rating, setRating] = useState(existing?.rating ?? 0);
  const [media, setMedia] = useState<string[]>(existing?.media.map(m => m.path) ?? []);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null);
  const [open, setOpen] = useState(!existing);

  const upload = async (files: FileList) => {
    setBusy(true);
    try {
      for (const file of Array.from(files).slice(0, 6 - media.length)) {
        const body = new FormData();
        body.append('kind', 'review');
        body.append('file', file);
        const res = await fetch('/api/account/upload', { method: 'POST', body });
        const data: { path?: string; error?: string } = await res.json();
        if (!res.ok || !data.path) throw new Error(data.error || 'Upload failed');
        setMedia(current => [...current, data.path!]);
      }
    } catch (e) {
      setMessage({ ok: false, text: e instanceof Error ? e.message : 'Upload failed' });
    } finally {
      setBusy(false);
      if (fileRef.current) fileRef.current.value = '';
    }
  };

  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setBusy(true);
    const data = new FormData(event.currentTarget);
    data.set('product_id', String(productId));
    media.forEach(path => data.append('media', path));
    const result = await runAction(() => saveReviewAction(data));
    setBusy(false);
    setMessage({ ok: result.ok, text: result.message ?? '' });
    if (result.ok) router.refresh();
  };

  const remove = async () => {
    if (!existing) return;
    setBusy(true);
    const data = new FormData();
    data.set('id', String(existing.id));
    const result = await runAction(() => deleteReviewAction(data));
    setBusy(false);
    setMessage({ ok: result.ok, text: result.message ?? '' });
    if (result.ok) { setOpen(false); router.refresh(); }
  };

  if (!open) {
    return (
      <div className="lum-review-mine">
        <div>
          <Stars value={existing!.rating} />
          <span className="lum-review-state"> Your review · {existing!.status}</span>
        </div>
        <button className="lum-cta-ghost" onClick={() => setOpen(true)}>Edit your review</button>
      </div>
    );
  }

  return (
    <form className="lum-review-form" onSubmit={submit}>
      <h3 className="lum-cart-summary-title">
        {existing ? 'Edit your review' : 'Review this piece'}
      </h3>

      <div className="lum-field">
        <span>Your rating *</span>
        <Stars value={rating} size={26} onPick={setRating} />
      </div>

      <label className="lum-field">
        <span>Title</span>
        <input name="title" defaultValue={existing?.title ?? ''} maxLength={150}
          placeholder="Exquisite in daylight" />
      </label>
      <label className="lum-field">
        <span>Your review *</span>
        <textarea name="body" rows={4} defaultValue={existing?.body ?? ''} maxLength={4000}
          placeholder="How does it wear? How did it arrive?" required />
      </label>

      <div className="lum-field">
        <span>Photos or video (up to 6)</span>
        <div className="lum-review-media">
          {media.map(path => (
            <div key={path} className="lum-review-thumb">
              {isVideo(path)
                ? <video src={path} muted playsInline preload="metadata" />
                // eslint-disable-next-line @next/next/no-img-element
                : <img src={path} alt="" />}
              <button type="button" aria-label="Remove this file"
                onClick={() => setMedia(current => current.filter(p => p !== path))}>
                <X size={12} />
              </button>
            </div>
          ))}
          {media.length < 6 && (
            <button type="button" className="lum-review-add" onClick={() => fileRef.current?.click()}
              disabled={busy}>
              <ImagePlus size={18} />
            </button>
          )}
        </div>
        <input ref={fileRef} type="file" accept="image/*,video/mp4,video/webm,video/quicktime"
          multiple style={{ display: 'none' }}
          onChange={e => { const f = e.target.files; if (f?.length) upload(f); }} />
        <em className="lum-field-hint">Photos up to 8 MB, video up to 25 MB.</em>
      </div>

      {message && (
        <div className={message.ok ? 'lum-account-notice' : 'lum-pdp-warn'}>{message.text}</div>
      )}
      <p className="lum-pdp-note">
        Reviews are read by our team before they appear. Editing an approved review sends it back for
        a fresh look.
      </p>

      <div className="lum-order-buttons">
        <button className="lum-cta-gold" disabled={busy || rating === 0}>
          {busy ? 'Sending…' : existing ? 'Update review' : 'Submit review'}
        </button>
        {existing && (
          <>
            <button type="button" className="lum-cta-ghost" disabled={busy} onClick={() => setOpen(false)}>
              Cancel
            </button>
            <button type="button" className="lum-cta-ghost lum-danger" disabled={busy} onClick={remove}>
              Delete
            </button>
          </>
        )}
      </div>
    </form>
  );
}
